In [41]:
from pathlib import Path
import pandas as pd 
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st

In [42]:
# Study data files
path = "train.csv"

# Read data and the study results
social_data = pd.read_csv(path)
social_data.head()

,User_ID,Age,Gender,Platform,Daily_Usage_Time (minutes),Posts_Per_Day,Likes_Received_Per_Day,Comments_Received_Per_Day,Messages_Sent_Per_Day,Dominant_Emotion
0,1,25,Female,Instagram,120.0,3.0,45.0,10.0,12.0,Happiness
1,2,30,Male,Twitter,90.0,5.0,20.0,25.0,30.0,Anger
2,3,22,Non-binary,Facebook,60.0,2.0,15.0,5.0,20.0,Neutral
3,4,28,Female,Instagram,200.0,8.0,100.0,30.0,50.0,Anxiety
4,5,33,Male,LinkedIn,45.0,1.0,5.0,2.0,10.0,Boredom

In [43]:
social_data.count()

User_ID                       1001
Age                           1001
Gender                        1000
Platform                      1000
Daily_Usage_Time (minutes)    1000
Posts_Per_Day                 1000
Likes_Received_Per_Day        1000
Comments_Received_Per_Day     1000
Messages_Sent_Per_Day         1000
Dominant_Emotion              1000
dtype: int64

In [44]:
gender_count = len(social_data["Gender"].unique())
print(gender_count)

19

In [47]:
social_data['Gender'].unique()

genders = ['Female', 'Male', 'Non-binary']
social_data[social_data['Age'].isin(genders)]


flipped = social_data[social_data['Age'].isin(genders)]
new = flipped.rename(columns={'Age': 'Gender1',
                            'Gender': 'Age',
                            'Gender1': 'Gender'})


filtered_data = social_data[~social_data['Age'].isin(genders)]
filtered_data

cleaned_data = pd.concat([filtered_data, new])

cleaned_data.dropna(subset=['Age', 'Gender'], inplace=True)

cleaned_data

,User_ID,Age,Gender,Platform,Daily_Usage_Time (minutes),Posts_Per_Day,Likes_Received_Per_Day,Comments_Received_Per_Day,Messages_Sent_Per_Day,Dominant_Emotion,Gender1
0,1,25,Female,Instagram,120.0,3.0,45.0,10.0,12.0,Happiness,NaN
1,2,30,Male,Twitter,90.0,5.0,20.0,25.0,30.0,Anger,NaN
2,3,22,Non-binary,Facebook,60.0,2.0,15.0,5.0,20.0,Neutral,NaN
3,4,28,Female,Instagram,200.0,8.0,100.0,30.0,50.0,Anxiety,NaN
4,5,33,Male,LinkedIn,45.0,1.0,5.0,2.0,10.0,Boredom,NaN
...,...,...,...,...,...,...,...,...,...,...,...
996,996,33,Non-binary,Twitter,85.0,4.0,35.0,18.0,18.0,Boredom,NaN
997,997,22,Female,Facebook,70.0,1.0,14.0,6.0,10.0,Neutral,NaN
998,998,35,Male,Whatsapp,110.0,3.0,50.0,25.0,25.0,Happiness,NaN
999,999,28,Non-binary,Telegram,60.0,2.0,18.0,8.0,18.0,Anger,NaN
1000,1000,27,Female,Snapchat,120.0,4.0,40.0,18.0,22.0,Neutral,NaN

In [48]:
print(len(cleaned_data['Gender'].unique()))

3

In [56]:
clean_data_frame = cleaned_data.iloc[:, [0, 1,2,3,4,5,6,7,8,9]]

In [57]:
clean_data_frame.to_csv('Clean_CSV.csv',index=False)